" --- Plug Scripts {{{
call plug#begin('~/.nvim/plugged')

source ~/.nvim/base/plugs.vim

Plug 'tpope/vim-obsession'

Plug 'benekastah/neomake'
Plug 'christoomey/vim-tmux-navigator'

Plug 'critiqjo/lldb.nvim'

call plug#end()
" --- Plug Scripts }}}

" --- Global Options {{{
source ~/.nvim/base/options.vim

set lazyredraw " Faster <C-o> mappings in insert mode with airline
set mouse=
" --- Global Options }}}

" --- Plugin Options {{{
source ~/.nvim/base/plugin-opts.vim
let g:tmux_navigator_no_mappings = 1
" --- Plugin Options }}}

" --- Keymaps {{{
source ~/.nvim/base/keymaps.vim

tnoremap zj <C-\><C-n>

" Make ZQ redoable!
nnoremap ZQ :call critiqjo#redoable_zq()<CR>

nmap <M-b> <Plug>LLBreakSwitch

nnoremap <silent> <M-h> :TmuxNavigateLeft<CR>
nnoremap <silent> <M-j> :TmuxNavigateDown<CR>
nnoremap <silent> <M-k> :TmuxNavigateUp<CR>
nnoremap <silent> <M-l> :TmuxNavigateRight<CR>

" --- Meta-keymaps mode-ict {{{
inoremap <M-b> <C-o>b
inoremap <M-B> <C-o>B
inoremap <M-d> <C-o>d
inoremap <M-e> <C-o>e<Right>
inoremap <M-E> <C-o>E<Right>
inoremap <M-f> <Esc>f
inoremap <M-F> <Esc>F
inoremap <M-o> <Esc>o
inoremap <M-O> <Esc>O
inoremap <M-t> <Esc>t
inoremap <M-T> <Esc>T
inoremap <M-u> <C-o>u
inoremap <M-w> <C-o>w
inoremap <M-W> <C-o>W
tnoremap <M-b> <Esc>b
tnoremap <M-d> <Esc>d
tnoremap <M-f> <Esc>f
tnoremap <M-F> <Esc>F
tnoremap <M-h> <Esc>h
tnoremap <M-j> <Esc>j
tnoremap <M-k> <Esc>k
tnoremap <M-l> <Esc>l
tnoremap <M-n> <Esc>n
tnoremap <M-p> <Esc>p
tnoremap <M-u> <Esc>u
tnoremap <M-w> <Esc>w
tnoremap <M-x> <Esc>x
" --- Meta-keymaps }}}
" --- Keymaps }}}

source ~/.nvim/base/misc.vim

" vim:fdm=marker:ts=2:sw=2
