#!/bin/bash

export SCRATCH=/dev/shm/$USER"_tmp"
feh --bg-fill /home/share/abstract-0$((RANDOM%7+1)).jpg

[[ -d $SCRATCH ]] || mkdir -p -m744 $SCRATCH
[[ -L ~/scratch ]] || ln -s $SCRATCH ~/scratch

cache_dir=$SCRATCH/.cache
[[ -d $cache_dir ]] || mkdir -p -m744 $cache_dir
[[ -L ~/.cache ]] || ln -s $cache_dir ~/

bash ~/mozilla_sync

#exec i3 -c ~/.config/i3/config >> ~/scratch/i3log 2>&1  # when in ~/.xinitrc

