#!/bin/bash

bash ~/.local/bin/rand-wall.sh
#bash ~/.local/bin/moz-init.sh
setxkbmap us -variant colemak
xmodmap -e "clear Lock"
compton -b --inactive-dim 0.1
i3-msg "workspace 1:neo; exec urxvtd -o -q -f && sleep 0.5 && urxvtc"
